appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 4j/xdXLantx2GvLN/CHGzGCfwUFee6IKsFZtpBRI0b9ZxFlXpiKE+ZqBoKPfD+0BPI5aCg0EiK/1xrzf8uhnn71qdFTK9Ev7q+ZQAtoUXPXCzGhgnZ5SehKXssmqxNsVzP8mWDpTuz03dr52XN6HL6uShLDvdLHvJzuOazVLn65GcS/eymoR8IZmkLGS5dPwDAH5HY9+LVHylVt+vYpQFAGSwFhM7KzxlUQebM6BYIOAUAPx6Fom6VSPOzYgXWNfxniIZ7wchydL5GI3IORR4Y++7wTlNVksT2zkicDN1ppKxKcab6sHnA9AbhuUnlWgXDNPffm+GyPnDGf6nSjBWgM+0ydoml7vAlPY5HfNrVs/vrsElabh9YSgWnwP+HDxLyNhrLXy/btzK2GYd+5qdcnwf+xfG0DOB8esxivqD40gaoY4mTBQKuBb7uKvxl1kqEgHRPRG2nxbAlyTx6QhMOMHNFcAv2WGC699YhWGo0UzpC8OVfACDm7TsQqldXDpu8vmjvvIwoG0WXPaa1/bsVVBTmIBelYSbH4AnyVn1kgTOJtESDjbuhcya8B34dpkewDY5OdsmzmHrj6YMmwjngSzDE4w8h3KBXyCbkdiXx6vGX2cghtT5UcX1pDX1oCSw59K6imdfU1osND9QjL9egVxX7H7bcIEZkr853VepJk=
